use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::config::{validate_git_ref, validate_relative_path, validate_release_branch_prefix};

pub const WORKFLOW_PATH: &str = ".github/workflows/release-glz.yml";

const CHECKOUT_SHA: &str = "3d3c42e5aac5ba805825da76410c181273ba90b1"; // v7.0.1
const SETUP_BEAM_SHA: &str = "54075bcc5e249e4758d363f27d099f55d843f124"; // v1.24.1
const UPLOAD_ARTIFACT_SHA: &str = "043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"; // v7.0.1
const DOWNLOAD_ARTIFACT_SHA: &str = "3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"; // v8.0.1
// Official distribution builds seal their exact tag commit into the binary.
// The fallback keeps source-tree tests deterministic; production builds set
// RELEASE_GLZ_ACTION_SHA in the pinned distribution workflow.
const RELEASE_GLZ_ACTION_SHA: &str = match option_env!("RELEASE_GLZ_ACTION_SHA") {
    Some(sha) => sha,
    None => "8a9f70631d5b74d39f119a4cde2d96b765ed66c1",
};
const WORKFLOW_STATE_PATH: &str = ".release-glz/workflow-state.json";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkflowSettings {
    pub default_branch: String,
    pub manifest_path: PathBuf,
    pub compiler: String,
    pub environment: String,
    pub registry_credential_env: String,
    pub release_branch_prefix: String,
    pub action_sha: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkflowMode {
    Check,
    Diff,
    Update,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct WorkflowOutcome {
    pub schema: String,
    pub path: String,
    pub changed: bool,
    pub written: bool,
    pub diff: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct WorkflowStateFile {
    schema: String,
    path: String,
    sha256: String,
}

pub fn default_action_sha() -> &'static str {
    RELEASE_GLZ_ACTION_SHA
}

pub fn render(default_branch: &str, manifest_path: &Path) -> String {
    render_configured(
        default_branch,
        manifest_path,
        "1.9.0",
        "release",
        "HEXPM_API_KEY",
        "release-glz/",
        RELEASE_GLZ_ACTION_SHA,
    )
    .expect("built-in workflow settings are valid")
}

pub fn render_configured(
    default_branch: &str,
    manifest_path: &Path,
    compiler: &str,
    environment: &str,
    registry_credential_env: &str,
    release_branch_prefix: &str,
    action_sha: &str,
) -> Result<String> {
    validate_git_ref(default_branch, "workflow default branch")?;
    if default_branch.starts_with("refs/") {
        bail!("workflow default branch must be a branch name, not a full ref");
    }
    validate_relative_path(manifest_path, "workflow manifest path")?;
    validate_release_branch_prefix(release_branch_prefix)?;
    let manifest = manifest_path.to_string_lossy().replace('\\', "/");
    validate_scalar(default_branch, "default branch", true)?;
    validate_scalar(&manifest, "manifest path", true)?;
    validate_scalar(environment, "approval environment", false)?;
    validate_environment_name(registry_credential_env, "registry credential environment")?;
    validate_scalar(release_branch_prefix, "release branch prefix", true)?;
    compiler
        .parse::<semver::Version>()
        .context("workflow compiler must be an exact semantic version")?;
    if action_sha.len() != 40 || !action_sha.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        bail!("release-glz Action must be pinned to a full commit SHA");
    }
    Ok(format!(
        r#"# Generated by release-glz. Re-run `release-glz init` to refresh.
name: release-glz

on:
  push:
    branches: [{default_branch}]
  pull_request:
    branches: [{default_branch}]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      source-sha:
        description: Full commit SHA to release
        required: true
        type: string
      reason:
        description: Reason for the manual release
        required: true
        type: string
      candidate-digest:
        description: Candidate digest for explicit promotion
        required: false
        type: string

permissions: {{}}

concurrency:
  group: release-glz-${{{{ github.repository }}}}-{manifest}
  cancel-in-progress: false

jobs:
  plan:
    name: Observe release intent
    if: ${{{{ github.event_name != 'pull_request' }}}}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: read
    outputs:
      release-required: ${{{{ steps.plan.outputs.release-required }}}}
      version: ${{{{ steps.plan.outputs.version }}}}
    steps:
      - uses: actions/checkout@{CHECKOUT_SHA} # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{{{ inputs.source-sha || github.sha }}}}
          persist-credentials: false
      - uses: erlef/setup-beam@{SETUP_BEAM_SHA} # v1.24.1
        with:
          otp-version: "28.0"
          gleam-version: "{compiler}"
      - uses: P4suta/release-glz@{action_sha}
        id: plan
        with:
          command: plan
          manifest-path: "{manifest}"
        env:
          {registry_credential_env}: ${{{{ secrets.{registry_credential_env} }}}}

  candidate:
    name: Build sealed Candidate
    needs: plan
    if: ${{{{ always() && (github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && startsWith(github.head_ref, '{release_branch_prefix}'))) && (github.event_name == 'pull_request' || (needs.plan.result == 'success' && (github.event_name == 'workflow_dispatch' || needs.plan.outputs.release-required == 'true'))) }}}}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: read
    outputs:
      release-required: ${{{{ needs.plan.outputs.release-required || 'true' }}}}
      version: ${{{{ steps.rehearse.outputs.version }}}}
      intent-digest: ${{{{ steps.rehearse.outputs.intent-digest }}}}
      candidate-digest: ${{{{ steps.rehearse.outputs.candidate-digest }}}}
      artifact-id: ${{{{ steps.upload.outputs.artifact-id }}}}
      artifact-digest: ${{{{ steps.upload.outputs.artifact-digest }}}}
    steps:
      - uses: actions/checkout@{CHECKOUT_SHA} # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{{{ inputs.source-sha || github.event.pull_request.head.sha || github.sha }}}}
          persist-credentials: false
      - uses: erlef/setup-beam@{SETUP_BEAM_SHA} # v1.24.1
        with:
          otp-version: "28.0"
          gleam-version: "{compiler}"
      - uses: P4suta/release-glz@{action_sha}
        id: rehearse
        with:
          command: rehearse
          manifest-path: "{manifest}"
          source-ref: ${{{{ inputs.source-sha || github.event.pull_request.head.sha || github.sha }}}}
          candidate: .release-glz/candidate
      - uses: actions/upload-artifact@{UPLOAD_ARTIFACT_SHA} # v7.0.1
        if: ${{{{ steps.rehearse.outcome == 'success' }}}}
        id: upload
        with:
          name: release-glz-candidate-${{{{ github.run_id }}}}
          path: .release-glz/candidate
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1

  authorize:
    name: Bind or verify Release PR intent
    needs: candidate
    if: ${{{{ always() && needs.candidate.result == 'success' && needs.candidate.outputs.candidate-digest != '' && (github.event_name == 'push' || github.event_name == 'pull_request') }}}}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      contents: read
      pull-requests: write
    outputs:
      state: ${{{{ steps.authorize.outputs.state }}}}
      pr-url: ${{{{ steps.authorize.outputs.pr-url }}}}
    steps:
      - uses: actions/checkout@{CHECKOUT_SHA} # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{{{ github.event.pull_request.head.sha || github.sha }}}}
          persist-credentials: false
      - uses: actions/download-artifact@{DOWNLOAD_ARTIFACT_SHA} # v8.0.1
        with:
          artifact-ids: ${{{{ needs.candidate.outputs.artifact-id }}}}
          path: .release-glz/candidate
          merge-multiple: true
      - uses: P4suta/release-glz@{action_sha}
        id: authorize
        with:
          command: release-pr
          manifest-path: "{manifest}"
          candidate: .release-glz/candidate
          dry-run: ${{{{ github.event_name == 'push' }}}}

  publish:
    name: Publish approved Candidate
    needs: [candidate, authorize]
    if: ${{{{ always() && needs.candidate.result == 'success' && needs.candidate.outputs.candidate-digest != '' && (github.event_name == 'workflow_dispatch' || (needs.authorize.result == 'success' && needs.authorize.outputs.state == 'awaiting_approval')) && (inputs.candidate-digest == '' || inputs.candidate-digest == needs.candidate.outputs.candidate-digest) }}}}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: {environment}
    permissions:
      actions: read
      contents: write
      id-token: write
      pull-requests: read
    steps:
      - uses: actions/checkout@{CHECKOUT_SHA} # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{{{ inputs.source-sha || github.sha }}}}
          persist-credentials: false
      - uses: actions/download-artifact@{DOWNLOAD_ARTIFACT_SHA} # v8.0.1
        with:
          artifact-ids: ${{{{ needs.candidate.outputs.artifact-id }}}}
          path: .release-glz/candidate
          merge-multiple: true
      - uses: P4suta/release-glz@{action_sha}
        id: verify
        with:
          command: verify
          manifest-path: "{manifest}"
          candidate: .release-glz/candidate
          online: "true"
      - uses: P4suta/release-glz@{action_sha}
        id: release
        with:
          command: release
          manifest-path: "{manifest}"
          candidate: .release-glz/candidate
        env:
          {registry_credential_env}: ${{{{ secrets.{registry_credential_env} }}}}
          RELEASE_GLZ_APPROVED_INTENT_DIGEST: ${{{{ needs.candidate.outputs.intent-digest }}}}
          RELEASE_GLZ_APPROVED_CANDIDATE_DIGEST: ${{{{ needs.candidate.outputs.candidate-digest }}}}
          RELEASE_GLZ_ACTIONS_ARTIFACT_ID: ${{{{ needs.candidate.outputs.artifact-id }}}}
          RELEASE_GLZ_ACTIONS_ARTIFACT_DIGEST: ${{{{ needs.candidate.outputs.artifact-digest }}}}
          RELEASE_GLZ_ENVIRONMENT: {environment}
          RELEASE_GLZ_MANUAL_SOURCE_SHA: ${{{{ inputs.source-sha }}}}
          RELEASE_GLZ_MANUAL_REASON: ${{{{ inputs.reason }}}}

  release-pr:
    name: Update rolling Release PR
    runs-on: ubuntu-latest
    if: ${{{{ github.event_name == 'push' }}}}
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@{CHECKOUT_SHA} # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: erlef/setup-beam@{SETUP_BEAM_SHA} # v1.24.1
        with:
          otp-version: "28.0"
          gleam-version: "{compiler}"
      - uses: P4suta/release-glz@{action_sha}
        with:
          command: release-pr
          manifest-path: "{manifest}"
        env:
          {registry_credential_env}: ${{{{ secrets.{registry_credential_env} }}}}
"#
    ))
}

fn validate_environment_name(value: &str, field: &str) -> Result<()> {
    let valid = !value.is_empty()
        && value.bytes().enumerate().all(|(index, byte)| match byte {
            b'A'..=b'Z' | b'_' => true,
            b'0'..=b'9' => index > 0,
            _ => false,
        });
    if !valid {
        bail!("{field} must be an uppercase environment variable name");
    }
    Ok(())
}

fn validate_scalar(value: &str, field: &str, slash_allowed: bool) -> Result<()> {
    if value.is_empty()
        || value.bytes().any(|byte| {
            !(byte.is_ascii_alphanumeric()
                || matches!(byte, b'-' | b'_' | b'.')
                || (slash_allowed && byte == b'/'))
        })
    {
        bail!("{field} contains characters that are unsafe in generated workflow YAML");
    }
    Ok(())
}

pub fn init(
    repo_root: &Path,
    manifest_path: &Path,
    default_branch: &str,
    dry_run: bool,
) -> Result<PathBuf> {
    let path = repo_root.join(WORKFLOW_PATH);
    if path.exists() {
        bail!(
            "`{}` already exists; release-glz will not overwrite it",
            path.display()
        );
    }
    if !dry_run {
        fs::create_dir_all(path.parent().expect("workflow parent"))?;
        fs::write(&path, render(default_branch, manifest_path))
            .with_context(|| format!("failed to write `{}`", path.display()))?;
    }
    Ok(path)
}

pub fn sync(
    repo_root: &Path,
    settings: &WorkflowSettings,
    mode: WorkflowMode,
) -> Result<WorkflowOutcome> {
    let path = repo_root.join(WORKFLOW_PATH);
    let rendered = render_configured(
        &settings.default_branch,
        &settings.manifest_path,
        &settings.compiler,
        &settings.environment,
        &settings.registry_credential_env,
        &settings.release_branch_prefix,
        &settings.action_sha,
    )?;
    let current = fs::read_to_string(&path).ok();
    let changed = current.as_deref() != Some(rendered.as_str());
    let diff = (mode == WorkflowMode::Diff && changed)
        .then(|| workflow_diff(current.as_deref().unwrap_or(""), &rendered));
    let mut written = false;

    if mode == WorkflowMode::Update && changed {
        if let Some(current) = &current {
            let state_path = repo_root.join(WORKFLOW_STATE_PATH);
            let state: WorkflowStateFile = fs::read(&state_path)
                .ok()
                .and_then(|bytes| serde_json::from_slice(&bytes).ok())
                .with_context(|| {
                    format!(
                        "`{}` exists without a valid managed-state record; refusing to overwrite a modified workflow",
                        path.display()
                    )
                })?;
            if state.schema != "workflow-state/v1"
                || state.path != WORKFLOW_PATH
                || state.sha256 != digest(current.as_bytes())
            {
                bail!(
                    "`{}` was modified after generation; refusing to overwrite it",
                    path.display()
                );
            }
        }
        atomic_write(&path, rendered.as_bytes())?;
        let state = WorkflowStateFile {
            schema: "workflow-state/v1".into(),
            path: WORKFLOW_PATH.into(),
            sha256: digest(rendered.as_bytes()),
        };
        atomic_write(
            &repo_root.join(WORKFLOW_STATE_PATH),
            &serde_json::to_vec(&state)?,
        )?;
        written = true;
    }

    Ok(WorkflowOutcome {
        schema: "workflow/v1".into(),
        path: WORKFLOW_PATH.into(),
        changed,
        written,
        diff,
    })
}

fn atomic_write(path: &Path, contents: &[u8]) -> Result<()> {
    let parent = path.parent().context("managed file has no parent")?;
    fs::create_dir_all(parent)?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    temporary.write_all(contents)?;
    temporary.as_file().sync_all()?;
    temporary
        .persist(path)
        .map_err(|error| error.error)
        .with_context(|| format!("failed to atomically write `{}`", path.display()))?;
    Ok(())
}

fn digest(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn workflow_diff(current: &str, rendered: &str) -> String {
    let mut output = format!("--- {WORKFLOW_PATH}\n+++ {WORKFLOW_PATH} (generated)\n");
    for line in current.lines() {
        output.push_str(&format!("-{line}\n"));
    }
    for line in rendered.lines() {
        output.push_str(&format!("+{line}\n"));
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn workflow_has_secretless_candidate_and_environment_scoped_publish_jobs() {
        let yaml = render("main", Path::new("gleam.toml"));
        serde_yaml::from_str::<serde_yaml::Value>(&yaml).unwrap();
        assert!(yaml.contains("fetch-depth: 0"));
        assert!(yaml.contains("persist-credentials: false"));
        assert!(yaml.contains("  plan:"));
        assert!(yaml.contains("  candidate:"));
        assert!(yaml.contains("startsWith(github.head_ref, 'release-glz/')"));
        assert!(yaml.contains("  publish:"));
        let candidate = yaml
            .split("  candidate:")
            .nth(1)
            .unwrap()
            .split("  publish:")
            .next()
            .unwrap();
        assert!(!candidate.contains("secrets."));
        assert!(!candidate.contains("HEXPM_API_KEY"));
        assert!(!candidate.contains("command: plan"));
        let plan = yaml
            .split("  plan:")
            .nth(1)
            .unwrap()
            .split("  candidate:")
            .next()
            .unwrap();
        assert!(plan.contains("HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}"));
        let publish = yaml.split("  publish:").nth(1).unwrap();
        assert!(publish.contains("environment: release"));
        assert!(publish.contains("id-token: write"));
        assert!(publish.contains("needs: [candidate, authorize]"));
        assert!(yaml.contains("timeout-minutes:"));
        assert!(yaml.contains("cancel-in-progress: false"));
        assert!(yaml.contains("artifact-id"));
        assert!(yaml.contains("artifact-digest"));
        assert!(yaml.contains("command: rehearse"));
        assert!(yaml.contains("command: release"));
        let candidate_source =
            "${{ inputs.source-sha || github.event.pull_request.head.sha || github.sha }}";
        assert_eq!(
            yaml.matches(candidate_source).count(),
            2,
            "candidate checkout and rehearsal must bind the same event SHA"
        );
    }

    #[test]
    fn every_external_action_is_pinned_to_a_full_commit_sha() {
        let yaml = render("main", Path::new("gleam.toml"));
        for line in yaml.lines().filter(|line| {
            line.trim_start()
                .trim_start_matches("- ")
                .starts_with("uses:")
        }) {
            let reference = line
                .split_once('@')
                .unwrap_or_else(|| panic!("missing pin: {line}"))
                .1
                .split_whitespace()
                .next()
                .unwrap();
            assert_eq!(reference.len(), 40, "mutable action reference: {line}");
            assert!(
                reference.bytes().all(|byte| byte.is_ascii_hexdigit()),
                "{line}"
            );
        }
    }

    #[test]
    fn workflow_routes_pr_binding_merge_approval_and_manual_promotion_separately() {
        let yaml = render("main", Path::new("gleam.toml"));
        assert!(yaml.contains("  pull_request:"));
        assert!(yaml.contains("  authorize:"));
        let authorize = yaml
            .split("  authorize:")
            .nth(1)
            .unwrap()
            .split("  publish:")
            .next()
            .unwrap();
        assert!(authorize.contains("command: release-pr"));
        assert!(authorize.contains("candidate: .release-glz/candidate"));
        assert!(authorize.contains("github.event_name == 'pull_request'"));
        assert!(authorize.contains("dry-run: ${{ github.event_name == 'push' }}"));

        let publish = yaml
            .split("  publish:")
            .nth(1)
            .unwrap()
            .split("  release-pr:")
            .next()
            .unwrap();
        assert!(publish.contains("needs: [candidate, authorize]"));
        assert!(publish.contains("needs.authorize.outputs.state == 'awaiting_approval'"));
        assert!(publish.contains("github.event_name == 'workflow_dispatch'"));
        assert!(publish.contains("artifact-ids: ${{ needs.candidate.outputs.artifact-id }}"));
        assert!(publish.contains(
            "RELEASE_GLZ_ACTIONS_ARTIFACT_ID: ${{ needs.candidate.outputs.artifact-id }}"
        ));
        assert!(publish.contains(
            "RELEASE_GLZ_ACTIONS_ARTIFACT_DIGEST: ${{ needs.candidate.outputs.artifact-digest }}"
        ));

        let rolling_pr = yaml.split("  release-pr:").nth(1).unwrap();
        assert!(rolling_pr.contains("github.event_name == 'push'"));
        assert!(!rolling_pr.contains("needs: [candidate, publish]"));
    }

    #[test]
    fn configured_compiler_environment_and_action_commit_are_rendered_exactly() {
        let action_sha = "abcdef0123456789abcdef0123456789abcdef01";
        let yaml = render_configured(
            "trunk",
            Path::new("packages/widget/gleam.toml"),
            "1.18.1",
            "hex-production",
            "PRIVATE_HEX_TOKEN",
            "delivery/",
            action_sha,
        )
        .unwrap();
        assert!(yaml.contains("branches: [trunk]"));
        assert!(yaml.contains("gleam-version: \"1.18.1\""));
        assert!(yaml.contains("environment: hex-production"));
        assert!(yaml.contains("PRIVATE_HEX_TOKEN: ${{ secrets.PRIVATE_HEX_TOKEN }}"));
        assert!(!yaml.contains("HEXPM_API_KEY"));
        assert!(yaml.contains("startsWith(github.head_ref, 'delivery/')"));
        assert!(yaml.contains(&format!("P4suta/release-glz@{action_sha}")));
    }

    #[test]
    fn configured_workflow_rejects_paths_and_refs_that_change_repository_scope() {
        let valid_sha = "abcdef0123456789abcdef0123456789abcdef01";
        for (branch, manifest, prefix) in [
            ("main", "/tmp/gleam.toml", "release-glz/"),
            ("main", "../gleam.toml", "release-glz/"),
            ("main", "packages/../gleam.toml", "release-glz/"),
            ("refs/heads/main", "gleam.toml", "release-glz/"),
            ("main", "gleam.toml", "refs/heads/release/"),
            ("main", "gleam.toml", "release/../other/"),
        ] {
            assert!(
                render_configured(
                    branch,
                    Path::new(manifest),
                    "1.18.1",
                    "release",
                    "HEXPM_API_KEY",
                    prefix,
                    valid_sha,
                )
                .is_err(),
                "accepted branch={branch:?}, manifest={manifest:?}, prefix={prefix:?}"
            );
        }
    }

    #[test]
    fn managed_workflow_updates_only_when_the_existing_copy_is_unmodified() {
        let temp = tempfile::tempdir().unwrap();
        let settings = WorkflowSettings {
            default_branch: "main".into(),
            manifest_path: PathBuf::from("gleam.toml"),
            compiler: "1.18.1".into(),
            environment: "release".into(),
            registry_credential_env: "HEXPM_API_KEY".into(),
            release_branch_prefix: "release-glz/".into(),
            action_sha: "abcdef0123456789abcdef0123456789abcdef01".into(),
        };
        let created = sync(temp.path(), &settings, WorkflowMode::Update).unwrap();
        assert!(created.changed);
        let unchanged = sync(temp.path(), &settings, WorkflowMode::Check).unwrap();
        assert!(!unchanged.changed);

        let path = temp.path().join(WORKFLOW_PATH);
        fs::write(
            &path,
            format!("{}# user edit\n", fs::read_to_string(&path).unwrap()),
        )
        .unwrap();
        let mut newer = settings.clone();
        newer.compiler = "1.18.2".into();
        let error = sync(temp.path(), &newer, WorkflowMode::Update).unwrap_err();
        assert!(error.to_string().contains("modified"));
        assert!(fs::read_to_string(path).unwrap().contains("# user edit"));
    }

    #[test]
    fn workflow_scalar_environment_compiler_and_action_pins_fail_closed() {
        for valid in ["A", "_TOKEN", "TOKEN_2"] {
            validate_environment_name(valid, "test").unwrap();
        }
        for invalid in ["", "0TOKEN", "token", "TOKEN-NAME", "TOKEN NAME"] {
            assert!(validate_environment_name(invalid, "test").is_err());
        }
        validate_scalar("packages/widget", "test", true).unwrap();
        validate_scalar("release-prod", "test", false).unwrap();
        assert!(validate_scalar("release/prod", "test", false).is_err());
        for invalid in ["", "unsafe value", "value:\nsecret", "å"] {
            assert!(validate_scalar(invalid, "test", true).is_err());
        }

        let valid_sha = "abcdef0123456789abcdef0123456789abcdef01";
        for (compiler, environment, credential, action_sha) in [
            ("latest", "release", "HEXPM_API_KEY", valid_sha),
            ("1.18.1", "release/prod", "HEXPM_API_KEY", valid_sha),
            ("1.18.1", "release", "hex_token", valid_sha),
            ("1.18.1", "release", "HEXPM_API_KEY", "abc"),
            (
                "1.18.1",
                "release",
                "HEXPM_API_KEY",
                "gggggggggggggggggggggggggggggggggggggggg",
            ),
        ] {
            assert!(
                render_configured(
                    "main",
                    Path::new("gleam.toml"),
                    compiler,
                    environment,
                    credential,
                    "release-glz/",
                    action_sha,
                )
                .is_err()
            );
        }
    }

    #[test]
    fn legacy_init_is_non_destructive_in_dry_write_and_existing_modes() {
        let temp = tempfile::tempdir().unwrap();
        let path = init(temp.path(), Path::new("gleam.toml"), "main", true).unwrap();
        assert_eq!(path, temp.path().join(WORKFLOW_PATH));
        assert!(!path.exists());

        init(temp.path(), Path::new("gleam.toml"), "main", false).unwrap();
        assert!(path.exists());
        let original = fs::read(&path).unwrap();
        assert!(init(temp.path(), Path::new("gleam.toml"), "main", false).is_err());
        assert_eq!(fs::read(path).unwrap(), original);
    }

    #[test]
    fn managed_workflow_modes_report_and_apply_only_verified_state() {
        let settings = test_settings();
        let temp = tempfile::tempdir().unwrap();

        let check = sync(temp.path(), &settings, WorkflowMode::Check).unwrap();
        assert!(check.changed);
        assert!(!check.written);
        assert!(check.diff.is_none());

        let diff = sync(temp.path(), &settings, WorkflowMode::Diff).unwrap();
        assert!(diff.changed);
        assert!(!diff.written);
        let diff = diff.diff.unwrap();
        assert!(diff.starts_with(&format!("--- {WORKFLOW_PATH}")));
        assert!(diff.contains("+# Generated by release-glz"));

        let created = sync(temp.path(), &settings, WorkflowMode::Update).unwrap();
        assert!(created.written);
        let unchanged = sync(temp.path(), &settings, WorkflowMode::Diff).unwrap();
        assert!(!unchanged.changed);
        assert!(unchanged.diff.is_none());

        let mut updated = settings.clone();
        updated.compiler = "1.18.2".into();
        let outcome = sync(temp.path(), &updated, WorkflowMode::Update).unwrap();
        assert!(outcome.changed);
        assert!(outcome.written);
        assert!(
            fs::read_to_string(temp.path().join(WORKFLOW_PATH))
                .unwrap()
                .contains("gleam-version: \"1.18.2\"")
        );
    }

    #[test]
    fn managed_state_schema_path_and_digest_are_each_required_before_overwrite() {
        for case in ["missing", "malformed", "schema", "path", "digest"] {
            let temp = tempfile::tempdir().unwrap();
            let settings = test_settings();
            sync(temp.path(), &settings, WorkflowMode::Update).unwrap();
            let state_path = temp.path().join(WORKFLOW_STATE_PATH);
            match case {
                "missing" => fs::remove_file(&state_path).unwrap(),
                "malformed" => fs::write(&state_path, b"not json").unwrap(),
                "schema" | "path" | "digest" => {
                    let mut state: WorkflowStateFile =
                        serde_json::from_slice(&fs::read(&state_path).unwrap()).unwrap();
                    match case {
                        "schema" => state.schema = "workflow-state/v2".into(),
                        "path" => state.path = ".github/workflows/other.yml".into(),
                        "digest" => state.sha256 = "0".repeat(64),
                        _ => unreachable!(),
                    }
                    fs::write(&state_path, serde_json::to_vec(&state).unwrap()).unwrap();
                }
                _ => unreachable!(),
            }
            let mut changed = settings;
            changed.compiler = "1.18.2".into();
            assert!(
                sync(temp.path(), &changed, WorkflowMode::Update).is_err(),
                "accepted invalid workflow state {case}"
            );
        }
    }

    fn test_settings() -> WorkflowSettings {
        WorkflowSettings {
            default_branch: "main".into(),
            manifest_path: PathBuf::from("gleam.toml"),
            compiler: "1.18.1".into(),
            environment: "release".into(),
            registry_credential_env: "HEXPM_API_KEY".into(),
            release_branch_prefix: "release-glz/".into(),
            action_sha: "abcdef0123456789abcdef0123456789abcdef01".into(),
        }
    }

    #[test]
    fn repository_workflows_and_action_metadata_are_valid_yaml() {
        for source in [
            include_str!("../.github/workflows/ci.yml"),
            include_str!("../.github/workflows/distribute.yml"),
            include_str!("../action.yml"),
        ] {
            serde_yaml::from_str::<serde_yaml::Value>(source).unwrap();
        }
        for source in [
            include_str!("../.github/workflows/ci.yml"),
            include_str!("../.github/workflows/distribute.yml"),
        ] {
            for line in source.lines().filter(|line| {
                line.trim_start()
                    .trim_start_matches("- ")
                    .starts_with("uses:")
            }) {
                let reference = line
                    .split_once('@')
                    .unwrap()
                    .1
                    .split_whitespace()
                    .next()
                    .unwrap();
                assert_eq!(reference.len(), 40, "mutable repository Action: {line}");
                assert!(
                    reference.bytes().all(|byte| byte.is_ascii_hexdigit()),
                    "{line}"
                );
            }
        }
    }
}
